// Vercel serverless function: text description → gradient, generated by Claude.
// Needs ANTHROPIC_API_KEY in the Vercel project's environment variables.
// Without it the endpoint answers 503 and the app uses its built-in keyword generator.
import Anthropic from '@anthropic-ai/sdk';
import { AI_SCHEMA, MAX_PROMPT, SYSTEM_PROMPT, sanitizeAi } from '../src/lib/aiSchema';

// Best-effort per-instance rate limit so a public site can't be used to run up the bill.
const WINDOW_MS = 60_000;
const MAX_PER_WINDOW = 8;
const hits = new Map<string, number[]>();

function limited(ip: string): boolean {
  const now = Date.now();
  const recent = (hits.get(ip) ?? []).filter((t) => now - t < WINDOW_MS);
  recent.push(now);
  hits.set(ip, recent);
  if (hits.size > 5000) hits.clear();
  return recent.length > MAX_PER_WINDOW;
}

const json = (body: unknown, status = 200) => Response.json(body, { status, headers: { 'cache-control': 'no-store' } });

export async function POST(request: Request): Promise<Response> {
  if (!process.env.ANTHROPIC_API_KEY) return json({ error: 'AI generation is not configured on this deployment.' }, 503);

  const ip = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? 'unknown';
  if (limited(ip)) return json({ error: 'Too many requests. Try again in a minute.' }, 429);

  let prompt = '';
  try {
    const body = (await request.json()) as { prompt?: unknown };
    prompt = typeof body.prompt === 'string' ? body.prompt.trim().slice(0, MAX_PROMPT) : '';
  } catch {
    return json({ error: 'Send JSON: { "prompt": "..." }' }, 400);
  }
  if (!prompt) return json({ error: 'Describe a scene or a mood first.' }, 400);

  const client = new Anthropic();
  try {
    const response = await client.beta.messages.create({
      model: 'claude-opus-5',
      max_tokens: 4000,
      betas: ['server-side-fallback-2026-07-01'],
      fallbacks: 'default',
      output_config: { effort: 'low', format: { type: 'json_schema', schema: AI_SCHEMA } },
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: prompt }],
    });

    if (response.stop_reason === 'refusal') return json({ error: 'That description could not be turned into a gradient. Try another.' }, 422);
    const textBlock = response.content.find((b) => b.type === 'text');
    const gradient = sanitizeAi(textBlock && textBlock.type === 'text' ? JSON.parse(textBlock.text) : null);
    if (!gradient) return json({ error: 'The generated gradient was not usable. Try again.' }, 502);
    return json({ gradient, model: response.model });
  } catch (error) {
    if (error instanceof Anthropic.RateLimitError) return json({ error: 'The AI is busy. Try again in a moment.' }, 429);
    if (error instanceof Anthropic.AuthenticationError) return json({ error: 'AI generation is misconfigured (API key rejected).' }, 503);
    if (error instanceof Anthropic.APIError) return json({ error: `AI request failed (${error.status}).` }, 502);
    if (error instanceof SyntaxError) return json({ error: 'The generated gradient was not usable. Try again.' }, 502);
    return json({ error: 'AI request failed.' }, 500);
  }
}
